# Site settings
title: Datt
email: ryanxcharles+dattform@gmail.com
url: https://dattnetwork.github.io/datt.co
baseurl: /datt.co
description: ""

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#404040'
  links: '#219ab3'

# Footer settings
footer: Datt

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/dattnetwork
  - title: github
    url: https://github.com/dattnetwork

# Build settings
markdown: kramdown
permalink: pretty
